#!/bin/bash

# koristiti kao "$ checker ime_zadatka", npr "$ checker aliens"
# potrebno je imati "ime_zadatka.cpp" kao i "ime_zadatka_tests" folder

# u "ime_zadatka_tests" potrebno je imati sve test primjere
# te svaki test primjer mora imati dva odgovarajaca file-a, input i output
# npr, "xyz.in" i "xyz.out"

# pri potrebi za koristenjem kao komanda, dodati u /bin/ folder

arg=$1
path="$arg"_tests

comp $arg

if [[ $? ]]; then
	echo "$arg.cpp successfully compiled"
else
	echo "$arg.cpp failed during compilation"
fi

wa=0
cnt=0

flag=0
remb=0

echo "program failed on following tests:"

for i in "$path"/*.in*; do
	if [ -f $i ]; then
		j=${i/in/out}
		./$arg < $i > temp_file

		diff -w temp_file $j

		tmp=$? 
		if [ $tmp -eq 1 ]; then
			tmp2=${i/$path\//}
			if [ $flag -eq 0 ]; then
				remb=$tmp2
				flag=1
			fi	
			echo "$tmp2" 
		fi

		wa=$(( $wa + $tmp ))
		cnt=$(( $cnt + 1 ))
	fi
done

echo "$(( $cnt - $wa )) / $cnt successful runs"

if [ $flag -eq 1 ]; then
	echo "$remb"
fi

rm temp_file

